export * from './Login/Login'
export * from './landing'
export * from './Register/Register'
export * from './Dashboard/Dashboard'
export * from './Feed/Feed'
export * from './Profile/Profile'
export * from './Search/Search'